# Generated by Django 4.1.6 on 2023-07-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('bookingfordate', models.CharField(max_length=225)),
                ('time', models.CharField(max_length=225)),
                ('amounts', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('pref', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=255)),
                ('sensortypeandsize', models.CharField(max_length=255)),
                ('lensetype', models.CharField(max_length=255)),
                ('connectiontype', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('amountperday', models.CharField(max_length=255)),
                
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=225)),
                ('image', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('artice_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField(max_length=11)),
                ('receiver_id', models.IntegerField(max_length=11)),
                ('message', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='photographer',
            fields=[
                ('photographer_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=7)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('logins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.login')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('logins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.login')),
            ],
        ),
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('bookingss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.booking')),
            ],
        ),
        migrations.CreateModel(
            name='studio',
            fields=[
                ('studio_id', models.AutoField(primary_key=True, serialize=False)),
                ('studioname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('since', models.CharField(max_length=225)),
                ('licence', models.CharField(max_length=225)),
                ('logins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.login')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=225)),
                ('amount', models.CharField(max_length=225)),
                ('details', models.CharField(max_length=225)),
                ('image', models.CharField(max_length=1000)),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.category')),
                ('studios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.studio')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('photographers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.photographer')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.user')),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('requestedfor', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cameras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.camera')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.user')),
            ],
        ),
        migrations.AddField(
            model_name='photographer',
            name='studios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.studio'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.booking')),
            ],
        ),
        migrations.CreateModel(
            name='mywork',
            fields=[
                ('mywork_id', models.AutoField(primary_key=True, serialize=False)),
                ('works', models.CharField(max_length=255)),
                ('files', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.category')),
                ('studios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.studio')),
            ],
        ),
        migrations.CreateModel(
            name='protfolio',
            fields=[
                ('protfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('files', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=255)),
                ('photographers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaints', models.CharField(max_length=255)),
                ('reply', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.user')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='studios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.studio'),
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.user'),
        ),
        migrations.CreateModel(
            name='assignphoto',
            fields=[
                ('assignphoto_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.booking')),
                ('photographers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('artice_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('photographers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app5.photographer')),
            ],
        ),
    ]
