# Generated by Django 4.2.1 on 2023-08-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='photographers',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app5.photographer'),
            preserve_default=False,
        ),
    ]
