# Generated by Django 4.2.1 on 2023-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_booking_photographers'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_img',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
