# Generated by Django 4.2.1 on 2023-08-07 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_camera_cam_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='protfolio',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app5.category'),
            preserve_default=False,
        ),
    ]
